namespace ToolMod;

using System;
using System.IO;
using System.IO.Pipes;
using System.Threading;
using System.Threading.Tasks;

/// <summary>
/// generated by AI
/// 命名管道服务端（单连接），全部在后台线程运行
/// </summary>
public class DataSync : IDisposable
{
    private readonly string _pipeName;
    private NamedPipeServerStream _pipeStream;
    private StreamReader _reader;
    private StreamWriter _writer;
    private CancellationTokenSource _cts;
    private Task _serverTask;
    private bool _isRunning;
    private readonly object _lock = new object();
    private bool _disposed;

    // 对外事件
    public event EventHandler Connected;
    public event EventHandler<string> MessageReceived;
    public event EventHandler Disconnected;
    public event EventHandler<Exception> ErrorOccurred;

    public DataSync(string pipeName)
    {
        _pipeName = pipeName ?? throw new ArgumentNullException(nameof(pipeName));
    }

    /// <summary>
    /// 启动服务（立即返回，后台线程等待连接）
    /// </summary>
    public void Start()
    {
        if (_isRunning) return;
        lock (_lock)
        {
            if (_isRunning) return;
            _isRunning = true;
            _cts = new CancellationTokenSource();
            _serverTask = Task.Run(() => RunServerAsync(_cts.Token));
        }
    }

    /// <summary>
    /// 停止服务（立即返回，断开连接并终止后台线程）
    /// </summary>
    public void Stop()
    {
        try
        {
            lock (_lock)
            {
                if (!_isRunning) return;
                _isRunning = false;
                _cts?.Cancel();
                // 强制释放管道资源，使后台循环退出
                _pipeStream?.Dispose();
                _reader?.Dispose();
                _writer?.Dispose();
            }

            try
            {
                _serverTask?.Wait(TimeSpan.FromSeconds(2));
            }
            catch
            {
            }
        }
        catch (ObjectDisposedException e)
        {
        }
    }

    /// <summary>
    /// 向客户端发送消息（异步，线程安全）
    /// </summary>
    public async Task SendAsync(string message)
    {
        if (string.IsNullOrEmpty(message))
            throw new ArgumentNullException(nameof(message));
#if DEBUG
        ModCore.Instance.Log.LogMessage($"Received Command from Modifier UI: \n{message}");
#endif
        StreamWriter writer;
        lock (_lock)
        {
            if (!_isRunning || _writer == null)
                throw new InvalidOperationException("服务端未启动或未连接");
            writer = _writer;
        }

        await writer.WriteLineAsync(message);
        await writer.FlushAsync();
    }

    private async Task RunServerAsync(CancellationToken cancellationToken)
    {
        try
        {
            // 创建只接受一个连接的管道
            _pipeStream = new NamedPipeServerStream(
                _pipeName,
                PipeDirection.InOut,
                1,
                PipeTransmissionMode.Message,
                PipeOptions.Asynchronous);

            // 等待连接（可取消）
            using (cancellationToken.Register(() => _pipeStream.Dispose()))
            {
                await _pipeStream.WaitForConnectionAsync(cancellationToken);
            }

            lock (_lock)
            {
                _reader = new StreamReader(_pipeStream);
                _writer = new StreamWriter(_pipeStream) { AutoFlush = true };
            }

            Connected?.Invoke(this, EventArgs.Empty);

            // 循环接收消息
            string message;
            while (!cancellationToken.IsCancellationRequested &&
                   (message = await _reader.ReadLineAsync()) != null)
            {
                MessageReceived?.Invoke(this, message);
            }
        }
        catch (OperationCanceledException)
        {
            // 正常停止
        }
        catch (Exception ex)
        {
            ErrorOccurred?.Invoke(this, ex);
        }
        finally
        {
            Cleanup();
            Disconnected?.Invoke(this, EventArgs.Empty);
            lock (_lock)
            {
                _isRunning = false;
            }
        }
    }

    private void Cleanup()
    {
        lock (_lock)
        {
            _reader?.Dispose();
            _writer?.Dispose();
            _pipeStream?.Dispose();
            _reader = null;
            _writer = null;
            _pipeStream = null;
        }
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        Stop();
        _cts?.Dispose();
    }
}